---
title: "DS Project Team 11"
author: "[Evan Patel, Daksh Verma, Saurabh Rane, Sujay Shah, Tejas Dighe, Maxine Attobrah]"
output: pdf_document
---

# DS Project Team 11


```{r setup, include = TRUE, warning = FALSE, message = FALSE}
# libraries needed
library(tidyverse)
library(dplyr)
library(reshape2)

# COLUMNS:
# age
# sex
# bmi
# children
# smoker
# region
# charges

```

## Inital wrangling of data and some analysis


```{r, warning = FALSE, message = FALSE}
#data
insurance <- read_csv("insurance.csv")

head(insurance)

# check if any NAs in data
(find_nas <- apply(insurance,2, function(x) any(is.na(x))))
find_nas

```



```{r, warning = FALSE, message = FALSE}
# Age

# maximum age
max(insurance$age)

# minimum age
min(insurance$age)

# display the varying ages
ggplot(insurance, aes(x=age)) +
  geom_bar()+
  labs(title="Title: Age")

```


```{r, warning = FALSE, message = FALSE}
# Number of smokers

# display the number of userrs in different countries and which country has the most users

ggplot(insurance, aes(x=smoker)) +
  geom_bar()+
  geom_text(aes(label=stat(count)), stat="count", vjust=1.5, colour="red")+
  labs(title="Title: Smokers")

```


```{r, warning = FALSE, message = FALSE}

# display how many males vs females
ggplot(insurance, aes(x=sex, colour = age)) +
  geom_bar()+
  geom_text(aes(label=stat(count)), stat="count", vjust=1.5, colour="red")+
  labs(title="Title: Sex")

```


```{r, warning = FALSE, message = FALSE}

# display ages 
ggplot(insurance, aes(x=age, y=charges, colour = sex)) +
  geom_point() +
  labs(title="Title: Age vs Cost of Insuraunce")
```


```{r, warning = FALSE, message = FALSE}

# display ages 

insurance %>%
ggplot( aes(x=age, y=charges, fill=sex)) +
  geom_bar(stat="identity", position = position_dodge()) +
  labs(title="Title:Cost of Insurance (Female vs Male) ")


insurance %>%
  filter(sex=="female") %>%
ggplot( aes(x=age, y=charges)) +
  geom_bar(stat="identity") +
  labs(title="Title: Female Cost of Insurance ")


insurance %>%
  filter(sex=="male") %>%
ggplot( aes(x=age, y=charges)) +
  geom_bar(stat="identity") +
  labs(title="Title: Male Cost of Insurance ")

```


```{r, warning = FALSE, message = FALSE}

# display ages 
ggplot(insurance, aes(x=age, y=charges, colour = sex)) +
  geom_smooth() +
  labs(title="Title: Age vs Cost of Insurance")
```

```{r, warning = FALSE, message = FALSE}

# histograms 

insurance %>%
  filter(sex=="female") %>%
ggplot( aes(x=charges)) +
  geom_histogram() +
  labs(title="Title: Female Cost of Insurance ")


insurance %>%
  filter(sex=="female") %>%
ggplot( aes(x=log(charges))) +
  geom_histogram() +
  labs(title="Title: Female Cost of Insurance (log)")



insurance %>%
  filter(sex=="male") %>%
ggplot( aes(x=charges)) +
  geom_histogram() +
  labs(title="Title: Male Cost of Insurance  ")


insurance %>%
  filter(sex=="male") %>%
ggplot( aes(x=log(charges))) +
  geom_histogram() +
  labs(title="Title: Male Cost of Insurance (log) ")

```




```{r, warning = FALSE, message = FALSE}

# display gender and smoking habits 
# ggplot(insurance, aes(x=smoker, y=charges, colour = sex)) +
#  geom_boxplot() +
#  labs(title="Title: Smoker & Gender vs Cost of Insuraunce ")


# ggplot(insurance, aes(x=smoker, y=log(charges), colour = sex)) +
#  geom_boxplot() +
#  labs(title="Title: Smoker & Gender vs log(Cost of Insuraunce)")
```



```{r, warning = FALSE, message = FALSE}

# display regions and smoking habits 
ggplot(insurance, aes(x=region, y=charges, colour = smoker)) +
  geom_boxplot() +
  labs(title="Title: Smoker & Region vs Cost of Insurance")


ggplot(insurance, aes(x=region, y=log(charges), colour = smoker)) +
  geom_boxplot() +
  labs(title="Title: Smoker & Region vs log(Cost of Insurance)")
```


```{r, warning = FALSE, message = FALSE}

# number of children people have
unique(insurance$children)

# how many regions are in dataset
unique(insurance$region)
```


```{r, warning = FALSE, message = FALSE}
# display difference of cost if insurance based on age and if they smoke
ggplot(insurance, aes(x=age, y=log(charges), colour = smoker)) +
  geom_jitter(width =.5, height=.5)+
  labs(title="Title: Cost of insurance based on age and smoker")
```



```{r, warning = FALSE, message = FALSE}

# display difference of cost if insurance based on age and number of children
ggplot(insurance, aes(x=children, y=charges)) +
  geom_jitter() +
  labs(title="Title: Cost of insurance based on age and number of children")
```

```{r, warning = FALSE, message = FALSE}

# display cost of insurance based on age and if they smoke
ggplot(data = insurance) +
  geom_point(mapping = aes(x = age, y = charges, color=smoker)) +
  # seperate data based on number of children. Each plot is the number of children the person has
  facet_wrap(~ children)

```


```{r message=FALSE, warning=TRUE}

# prepare dataset for correlation matrix
insurance_dataChange_for_correlation <- insurance

# if female make it a 1 but if male make it a 0
insurance_dataChange_for_correlation$sex <- ifelse(insurance_dataChange_for_correlation$sex=="female", 1,0)



# if smoker make it a 1 but if non-smoker make it a 0
insurance_dataChange_for_correlation$smoker <- ifelse(insurance_dataChange_for_correlation$smoker=="yes", 1,0)

# change regions to numbers
insurance_dataChange_for_correlation$region <- as.numeric(factor(insurance_dataChange_for_correlation$region))

#show entire dataset after updates
insurance_dataChange_for_correlation


# create correlation matrix
correlation_matrix <- round(cor(na.omit(insurance_dataChange_for_correlation)),2)

melted_correlation_matrix <- melt(correlation_matrix)

# plot correlation matrix as heatmap
ggplot(data=melted_correlation_matrix, aes(x=Var1, y=Var2, fill=value))+
  geom_tile()+geom_text(aes(x=Var2, y=Var1, label=value), color="white", size=2) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )+
  labs(title="Title: ALL REGIONS")

# Based on correlation values we can see which variables have a stronger influence on the dependent variable
# Regardless of sign, the higher the value the stronger the influence

# Based on the result smoker has the strongest influencer. 

```




```{r, warning = FALSE, message = FALSE}

# SOUTHWEST

# prepare dataset for correlation matrix
insurance_dataChange_for_correlation_region1  <- insurance %>%
  filter(insurance$region == "southwest")

# remove region column
insurance_dataChange_for_correlation_region1 <- select(insurance_dataChange_for_correlation_region1, -region)

# if female make it a 1 but if male make it a 0
insurance_dataChange_for_correlation_region1$sex <- ifelse(insurance_dataChange_for_correlation_region1$sex=="female", 1,0)

# if smoker make it a 1 but if non-smoker make it a 0
insurance_dataChange_for_correlation_region1$smoker <- ifelse(insurance_dataChange_for_correlation_region1$smoker=="yes", 1,0)



#show entire dataset after updates
insurance_dataChange_for_correlation_region1


# create correlation matrix
correlation_matrix <- round(cor(na.omit(insurance_dataChange_for_correlation_region1)),2)

melted_correlation_matrix <- melt(correlation_matrix)

# plot correlation matrix as heatmap
ggplot(data=melted_correlation_matrix, aes(x=Var1, y=Var2, fill=value))+
  geom_tile()+geom_text(aes(x=Var2, y=Var1, label=value), color="white", size=2) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )+
  labs(title="Title: SOUTHWEST")

# Based on correlation values we can see which variables have a stronger influence on the dependent variable
# Regardless of sign, the higher the value the stronger the influence
```

```{r, warning = FALSE, message = FALSE}

# SOUTHEAST

# prepare dataset for correlation matrix
insurance_dataChange_for_correlation_region1  <- insurance %>%
  filter(insurance$region == "southeast")

# remove region column
insurance_dataChange_for_correlation_region1 <- select(insurance_dataChange_for_correlation_region1, -region)

# if female make it a 1 but if male make it a 0
insurance_dataChange_for_correlation_region1$sex <- ifelse(insurance_dataChange_for_correlation_region1$sex=="female", 1,0)

# if smoker make it a 1 but if non-smoker make it a 0
insurance_dataChange_for_correlation_region1$smoker <- ifelse(insurance_dataChange_for_correlation_region1$smoker=="yes", 1,0)


#show entire dataset after updates
insurance_dataChange_for_correlation_region1


# create correlation matrix
correlation_matrix <- round(cor(na.omit(insurance_dataChange_for_correlation_region1)),2)

melted_correlation_matrix <- melt(correlation_matrix)

# plot correlation matrix as heatmap
ggplot(data=melted_correlation_matrix, aes(x=Var1, y=Var2, fill=value))+
  geom_tile()+geom_text(aes(x=Var2, y=Var1, label=value), color="white", size=2) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )+
  labs(title="Title: SOUTHEAST")

# Based on correlation values we can see which variables have a stronger influence on the dependent variable
# Regardless of sign, the higher the value the stronger the influence

```


```{r, warning = FALSE, message = FALSE}

# NORTHEAST

# prepare dataset for correlation matrix
insurance_dataChange_for_correlation_region1  <- insurance %>%
  filter(insurance$region == "northeast")

# remove region column
insurance_dataChange_for_correlation_region1 <- select(insurance_dataChange_for_correlation_region1, -region)

# if female make it a 1 but if male make it a 0
insurance_dataChange_for_correlation_region1$sex <- ifelse(insurance_dataChange_for_correlation_region1$sex=="female", 1,0)

# if smoker make it a 1 but if non-smoker make it a 0
insurance_dataChange_for_correlation_region1$smoker <- ifelse(insurance_dataChange_for_correlation_region1$smoker=="yes", 1,0)


#show entire dataset after updates
insurance_dataChange_for_correlation_region1


# create correlation matrix
correlation_matrix <- round(cor(na.omit(insurance_dataChange_for_correlation_region1)),2)

melted_correlation_matrix <- melt(correlation_matrix)

# plot correlation matrix as heatmap
ggplot(data=melted_correlation_matrix, aes(x=Var1, y=Var2, fill=value))+
  geom_tile()+geom_text(aes(x=Var2, y=Var1, label=value), color="white", size=2) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )+
  labs(title="Title: NORTHEAST")

# Based on correlation values we can see which variables have a stronger influence on the dependent variable
# Regardless of sign, the higher the value the stronger the influence

```



```{r, warning = FALSE, message = FALSE}

# NORTHWEST

# prepare dataset for correlation matrix
insurance_dataChange_for_correlation_region1  <- insurance %>%
  filter(insurance$region == "northwest")

# remove region column
insurance_dataChange_for_correlation_region1 <- select(insurance_dataChange_for_correlation_region1, -region)

# if female make it a 1 but if male make it a 0
insurance_dataChange_for_correlation_region1$sex <- ifelse(insurance_dataChange_for_correlation_region1$sex=="female", 1,0)

# if smoker make it a 1 but if non-smoker make it a 0
insurance_dataChange_for_correlation_region1$smoker <- ifelse(insurance_dataChange_for_correlation_region1$smoker=="yes", 1,0)


#show entire dataset after updates
insurance_dataChange_for_correlation_region1


# create correlation matrix
correlation_matrix <- round(cor(na.omit(insurance_dataChange_for_correlation_region1)),2)

melted_correlation_matrix <- melt(correlation_matrix)

# plot correlation matrix as heatmap
ggplot(data=melted_correlation_matrix, aes(x=Var1, y=Var2, fill=value))+
  geom_tile()+geom_text(aes(x=Var2, y=Var1, label=value), color="white", size=2) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )+
  labs(title="Title: NORTHWEST")

# Based on correlation values we can see which variables have a stronger influence on the dependent variable
# Regardless of sign, the higher the value the stronger the influence

```



```{r, warning = FALSE, message = FALSE}
insurance$log_charges = log(insurance$charges)
set.seed(100) 

index = sample(1:nrow(insurance), 0.8*nrow(insurance)) 

train = insurance[index,] # Create the training data

test = insurance[-index,] # Create the test data


library(glmnet)
# Getting the independent variable
x_train <- data.matrix(train[, c("smoker", "age", "bmi")])
# Getting the dependent variable
y_train <- data.matrix(train[,c("log_charges")])
x_test <- data.matrix(train[, c("smoker", "age", "bmi")])
# Getting the dependent variable
y_test <- data.matrix(train[,c("log_charges")])
# Setting the range of lambda values
lambda_seq <- 10^seq(2, -2, by = -.1)

# Using glmnet function to build the ridge regression in r
ridge <- glmnet(x_train, y_train, alpha = 0, lambda  = lambda_seq)
# Checking the model
summary(ridge)
ridge_cv <- cv.glmnet(x_train, y_train, alpha = 0, lambda = lambda_seq)
# Best lambda value
best_lambda_r <- ridge_cv$lambda.min
best_lambda_r
# Rebuilding the model with optimal lambda value
best_ridge <- glmnet(x_train, y_train, alpha = 0, lambda = best_lambda_r)
#Ridge Regression
#================
coef(best_ridge)

lasso <- glmnet(x_train, y_train, alpha = 1, lambda  = lambda_seq)
# Checking the model
summary(lasso)
lasso_cv <- cv.glmnet(x_train, y_train, alpha = 1, lambda = lambda_seq)
# Best lambda value
best_lambda_l <- lasso_cv$lambda.min
best_lambda_l
# Rebuilding the model with optimal lambda value
best_lasso <- glmnet(x_train, y_train, alpha = 1, lambda = best_lambda_l)
#Lasso Regression
#================
coef(best_lasso)

elastic <- glmnet(x_train, y_train, alpha = .5, lambda  = lambda_seq)
# Checking the model
summary(elastic)
elastic_cv <- cv.glmnet(x_train, y_train, alpha = .5, lambda = lambda_seq)
# Best lambda value
best_lambda_e <- elastic_cv$lambda.min
best_lambda_e 
# Rebuilding the model with optimal lambda value
best_elastic <- glmnet(x_train, y_train, alpha = .5, lambda = best_lambda_e)
#Elastic Regression
#================
coef(best_elastic)


resid_l <- c()
predictions_l <- predict(lasso, s = best_lambda_l, newx = x_test)
resid_l <- c(resid_l, predictions_l - y_test)
#Lasso Mean Squared Error
(mse.l <- mean(resid_l^2))

resid_r <- c()
predictions_r <- predict(ridge, s = best_lambda_r, newx = x_test)
resid_r <- c(resid_r, predictions_r - y_test)
#Ridge Mean Squared Error
(mse.r <- mean(resid_r^2))

resid_e <- c()
predictions_e <- predict(elastic, s = best_lambda_e, newx = x_test)
resid_e <- c(resid_e, predictions_e - y_test)
#Elastic Mean Squared Error
(mse.e <- mean(resid_e^2))

###########################
```
```{r, warning = FALSE, message = FALSE}

# OLS 

# install.packages("Metrics")
library('Metrics')

# split 80 percent of data to train  and 20 percent to test
split <- initial_split(insurance_dataChange_for_correlation, prop = .8)

# training data
ins_trainData = training(split)

# validation data
ins_valData = testing(split)

# linear regression using training data
linear_model <- lm(charges ~ bmi + smoker + age, data =ins_trainData)

# predictions using validation data
linear_model_predictions <- predict(linear_model, newx=ins_valData)

# summary of linear model
(linear_model_summary <- summary(linear_model) )

# mse using way taught in class
mean(( ins_valData$charges - linear_model_predictions  )^2)

# mse using metric library
mse(ins_valData$charges,linear_model_predictions)

```


```{r, warning = FALSE, message = FALSE}

library(randomForest)

print("Random Forest")
samples <- rep(1:5, length.out = nrow(x_train))

mse.rf <- c()
lowestMSE <- Inf
selectedTrees <- 0
selectedMTry <- 0

numTrees <- c(100, 200, 300, 400, 500)
numVarSplit <- c(1, 2, 3)
for(numTree in numTrees) {
  for(numVars in numVarSplit) {
    val.sq.rf <- c()
    for(k in 1:5){
      k_x_train <- x_train[samples != k, ]
      k_y_train <- y_train[samples != k, ]
      k_x_val <- x_train[samples == k, ]
      k_y_val <- y_train[samples == k,]
      
      rf <- randomForest(x = k_x_train, y = k_y_train, ntree=numTree, mtry=numVars)
      val.forest <- predict(rf, newdata = k_x_val)
    
      val.sq.rf <- c(val.sq.rf, (val.forest - k_y_val)^2)
    }
    mse.rf <- c(mse.rf, mean(val.sq.rf))
    
    if(mean(val.sq.rf) < lowestMSE) {
      lowestMSE <- mse.rf
      selectedMTry <- numVars
      selectedTrees <- numTree
    }

  }

}

print(mse.rf)
print(lowestMSE) 
print(selectedMTry)
print(selectedTrees)
```


```{r, warning = FALSE, message = FALSE}

(rf <- randomForest(x = k_x_train, y = k_y_train, ntree=selectedTrees, mtry=selectedMTry))
test.forest <- predict(rf, newdata = x_test)

test.sq.rf <- (test.forest - y_test)^2
test.mse <- mean(test.sq.rf)

print(test.mse)

```







